### ISSUE TITLE
This plugin disables framer's Properties widget!

### ISSUE THREAD

**Issue by mlaurita** [perrysmotors/copy-framer-code#11]
I love this plugin, except that when I paste the code into framer, the layer properties widget is disabled/disappears and I have not found a way to get it back.

Help!

<img width="90" alt="screen shot 2017-06-02 at 11 00 17 am" src="https://cloud.githubusercontent.com/assets/19198415/26731644/b58b5cd2-4782-11e7-9255-f004e946aa7e.png">

**Comment by perrysmotors** [comment]
Sorry to hear that. The whole point is you should be able to mess with the properties once they are in Framer! I think this is probably a Framer issue as once you are in Framer all you are doing is pasting code to the clipboard. It works fine for me. Are you getting code errors. Framer won't allow you to access the layer properties until the code errors are resolved. If you post a video on the Framer Facebook group I'll look out for it and see if I can work out what's happening and maybe someone else can help too.

**Comment by perrysmotors** [comment]
Hope you resolved your issue. I'll close as it looks like the problem is with Framer...

**Comment by mlaurita** [comment]
Hey Giles,

As of now the issue is still not resolved, but yes, it's probably to do with Framer. I'll keep trying!
