### ISSUE TITLE
Layers that have '$' at the start don't convert nicely into Framer Layer

### ISSUE THREAD

**Issue by Shaunm44** [perrysmotors/copy-framer-code#3]
In my sketch file, I have text with dollar amounts (i.e. "$10.52") and the layers are automatically named to match the text value. When Framer sees variables named `$10.52` and such it fails. See attached image.
![screen shot 2017-05-01 at 11 59 53 am](https://cloud.githubusercontent.com/assets/3894713/25590644/3bf59a16-2e66-11e7-91c4-399edc9b8eec.png)

**Comment by perrysmotors** [comment]
Thanks for letting me know. I need to think about how to handle layer names better.

**Comment by perrysmotors** [comment]
Should be fixed now. Please note you can't use Javascript keywords as layer names and layer names need to be unique.

**Comment by Shaunm44** [comment]
Thanks @perrysmotors! I was wondering about layer naming b/c I had an issue before with layer names and underscores (or spaces) with Framer. Any possibility you could use Framer's layer renaming code? Not sure if it's open source or anyway to find it.
