### ISSUE TITLE
small y offset with TextLayers

### ISSUE THREAD

**Issue by fx-lange** [perrysmotors/copy-framer-code#7]
I noticed a small y offset with TextLayers. In my example it was off by -3px. Not sure if it is Font and/or FontSize dependent. I'll try to add a proper example later.

**Comment by perrysmotors** [comment]
There are probably differences in the way Framer and Sketch render text. I've tested a design and the Framer text layer needed nudging up by 1px compared to the design exported @2x. But first check the fonts are included in your Framer project. If it's a Google Font you can use Utils.loadWebFont(). If not Utils.insertCSS('@import url(css/project.css)') and add a CSS file with @font-face definitions.
