### ISSUE TITLE
crashing on Sketch launch

### ISSUE THREAD

**Issue by tompiarulli** [perrysmotors/copy-framer-code#8]
It appears the plugin is causing Sketch to crash on launch in the latest version.

**Comment by perrysmotors** [comment]
Can you confirm a few things... Are you using the latest version of the plugin (v3.0.1)? When you say the latest version of Sketch, do you mean Sketch 44.1? Does Sketch stop crashing when the plugin is removed and start crashing when the plugin is re-installed?

**Comment by tompiarulli** [comment]
Yes to all of those questions, upon poking around it seems like its an issue with manifest.json

**Comment by perrysmotors** [comment]
In the last release I included an `appcastURL` entry in in the `manifest.json` file. This was to support a new mechanism for updating plugins in Sketch from v45 onwards. I'm not sure if this is causing Sketch v44.1 to crash but I have removed this entry in my latest release (v3.1). Can you update and let me know if this fixes the issue for you. Thanks for reporting the issue.

**Comment by perrysmotors** [comment]
I'd had confirmation from the guys at Sketch that `appcastURL` is causing problems and they are changing the property name to `appcast` to fix this.
